server:
  port: 8080
  context-path: /api

ribbon:
  eureka:
    enabled: false

user-service:
  ribbon:
    listOfServers: user-service:8081

todo-service:
  ribbon:
    listOfServers: todo-service:8082

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  debug:
    request: true
  routes:
    user:
      path: /users/**
      serviceId: user-service
      stripPrefix: false

    todos:
      path: /todos/**
      serviceId: todo-service
      stripPrefix: false
