#spring:
#  application:
#    name: gatway
#  cloud:
#    consul:
#      host: consul
#      port: 8500
#      discovery:
#        instance-id: ${spring.application.name}:${random.int}
#        health-check-path: /api/health


server:
  port: 8080
  context-path: /api

ribbon:
  eureka:
    enabled: false

user-service:
  ribbon:
    listOfServers: localhost:8081

todo-service:
  ribbon:
    listOfServers: localhost:8082


zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  debug:
    request: true
  routes:
    user:
      path: /users/**
#      url: http://localhost:8081
      serviceId: user-service
      stripPrefix: false
#    login:
#      path: /login/**
#      url: http://localhost:8081
#      stripPrefix: false
#    verifications:
#      path: verifications/**
#      url: http://localhost:8081
#      stripPrefix: false
    todos:
      path: /todos/**
#      url: http://localhost:8082
      serviceId: todo-service
      stripPrefix: false

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: TRACE